### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by sammo3182** [Vopaaz/CNKI_2_BibTeX#2]
Thank you again for the great module! 

Recently detected this empty output issue---it's more a CNKI's fault, though. Just have a check the attached `.net` file. I found, for some unknown reason, CNKI occasionally produces such NoteExpress files including multiple empty lines. In such case, your module may recognize them as broken file and produces empty `bibtex` files. I'm not sure whether it's worth your effort. After all, I fell into such case for only twice besides tens of successful cases. but, just leave an issue here, in case it can be fixed by an easy patch (Maybe just let the module omit the "Author address"? No journal would require that info).
[CNKI-636862711945718750.zip](https://github.com/Vopaaz/CNKI_2_BibTeX/files/2889600/CNKI-636862711945718750.zip)

**Comment by Vopaaz** [comment]
@sammo3182 
Hi, I have updated version 0.2.1 on PyPI and the code is pushed to Github. Please use pip to acquire the latest version and check out if the problem is resolved.

I have actually guessed that there may be exceptions in the `.net` file from CNKI since the beginning but it's impossible for me to test them all. Thank you for helping to improve this module.
Please feel free to contact me if you have further problems.
