### ISSUE TITLE
Bibtexkey for multiple authors

### ISSUE THREAD

**Issue by sammo3182** [Vopaaz/CNKI_2_BibTeX#3]
Thank you for updating the module responding to #2. I compile the new version and it successfully captured the info, yet produced an invalid bibtexkey as following:

```
@Article{XieXin,WangXiaoZeng2005,
	author = {谢昕,王小增},
	title = {基于公共行政理念的政府公共关系发展历程探析},
	journal = {湖北社会科学},
	year = {2005},
	authoraddress = {中国地质大学政法学院,中国地质大学政法学院 湖北武汉430074,湖北武汉430074},
	issue = {09},
	pages = {14-16},
	keywords = {政府公共关系;;公共行政;;发展历程;;理念},
	abstract = {在公共行政的历史长河中,政府公共关系是一个新生的事物,它伴随着公共行政的发展而发展,经历了传统公共行政阶段、正统公共行政阶段、新公共行政阶段和新公共管理阶段。改革开放20多年来,我国政府公关的意识已经初步确立并日益得到强化,将来会得到更快的发展。},
	ISBN = {1003-8477},
	ISSN = {1003-8477},
	notes = {42-1112/C},
	databaseprovider = {CNKI},
}
```
Any way to omit the comma in `XieXin,WangXiaoZeng2005`?
Thank you!

**Comment by Vopaaz** [comment]
This issue happens because it uses `,` as the separator in the author field, instead of the commonly used `;` or `;;`.

Version `0.2.2` fixes this problem. It also changes the separator of authors in the output bib file, from `,` to the standard `and`.
`author = {谢昕,王小增}` will be `author = {谢昕 and 王小增}` now.
